### ISSUE TITLE
Fails in 64 bit use

### ISSUE THREAD

**Issue by KennethFN** [henvb/SnappyWinscard#2]
Hi,
I've been trying to develop a 64 bit program runnning on my win10, but it appears that your nice wrapping of the winscard.dll, doesn't work in 64 bit.
is that true?

kind regards 
Kenneth Nielsen

**Comment by henvb** [comment]
Hi Kenneth,
I‘ll take a look into that tomorrow and will let you know!

**Comment by KennethFN** [comment]
I've tracked it to be a problem with winscard.dll, 64/32 bit..
and made a 32 RestAPI, to call
